// ACTIONS
export const ADD_GUEST_SESSION = 'ADD_GUEST_SESSION';
export const UPDATE_GUEST_SESSION_RATED_MOVIES = 'UPDATE_GUEST_SESSION_RATED_MOVIES';
export const SET_THEME = 'SET_THEME';

// LOCAL STORAGE
export const LOCAL_STORAGE_STORE_KEY = 'tmdb';
